"""Simulated-life ticker.

Called by /api/tick every ~4 hours (via free external cron). For each
onboarded user, evolves Yuki's buddy_state: mood, streak, weight (both
true and reported — this is where the deception mechanic actually fires),
plus a small chance of a new buddy_life event generated by the LLM.

Design notes
- Deterministic core (Python math + `random`), LLM only for the natural-
  language event description when we decide to emit one. Keeps cost at
  fractions of a cent per month.
- No timezone awareness yet: UTC across the board.
- Single-user in practice but the entry point iterates all users so the
  same code works when we grow.
- Silent. This step never sends a message. Proactive is Step 4.
"""
from __future__ import annotations

import json
import logging
import random
from datetime import datetime, timezone
from typing import Any

from yuki.db import (
    create_life_event,
    get_buddy_state,
    get_last_user_message_ts,
    list_all_users,
    list_recent_life_events,
    update_buddy_state,
)
from yuki.llm import LlmError, chat as llm_chat, is_enabled as llm_enabled
from yuki.memory import ingest_for_user
from yuki.roomread import refresh_for_user

logger = logging.getLogger(__name__)

MOODS = ("steady", "up", "down", "anxious", "excited", "tired", "hopeful", "off")
DOMAINS = ("study", "language", "social", "weight", "other")

# Rough transition table — from -> {to: weight}. Weights don't need to sum
# to 1, we normalise. Mood dips get slightly boosted if the user's been quiet.
_TRANSITIONS: dict[str, dict[str, float]] = {
    "steady":   {"steady": 55, "up": 12, "down": 8, "hopeful": 7, "tired": 7, "anxious": 4, "excited": 4, "off": 3},
    "up":       {"up": 40, "steady": 25, "hopeful": 15, "excited": 8, "down": 6, "tired": 6},
    "down":     {"down": 40, "steady": 20, "off": 15, "tired": 12, "anxious": 8, "up": 5},
    "anxious":  {"anxious": 35, "tired": 18, "steady": 18, "down": 12, "off": 10, "hopeful": 7},
    "excited":  {"excited": 30, "up": 25, "steady": 20, "hopeful": 15, "tired": 10},
    "tired":    {"tired": 40, "steady": 25, "down": 12, "off": 10, "hopeful": 8, "up": 5},
    "hopeful":  {"hopeful": 35, "up": 25, "steady": 22, "excited": 10, "down": 5, "tired": 3},
    "off":      {"off": 35, "down": 22, "tired": 18, "steady": 15, "anxious": 7, "hopeful": 3},
}

# When the user hasn't messaged in this many hours, tilt mood transitions
# slightly toward "off"/"down" (preview of Step 6 room-reading).
_QUIET_HOURS_THRESHOLD = 48
_QUIET_MOOD_BIAS = {"off": 6, "down": 4, "tired": 3}


def _weighted_pick(weights: dict[str, float]) -> str:
    items = list(weights.items())
    total = sum(w for _, w in items)
    r = random.uniform(0, total)
    acc = 0.0
    for name, w in items:
        acc += w
        if r <= acc:
            return name
    return items[-1][0]


def _next_mood(current: str, quiet_hours: float) -> str:
    base = _TRANSITIONS.get(current, _TRANSITIONS["steady"]).copy()
    if quiet_hours >= _QUIET_HOURS_THRESHOLD:
        for k, boost in _QUIET_MOOD_BIAS.items():
            base[k] = base.get(k, 0) + boost
    return _weighted_pick(base)


def _hours_since(iso_ts: str | None) -> float:
    if not iso_ts:
        return 9999.0
    try:
        # datetime.fromisoformat handles "+00:00" suffix
        t = datetime.fromisoformat(iso_ts)
        if t.tzinfo is None:
            t = t.replace(tzinfo=timezone.utc)
    except ValueError:
        return 9999.0
    return (datetime.now(timezone.utc) - t).total_seconds() / 3600.0


def _weight_step(
    true_weight: float, target_weight: float, days_to_deadline: float
) -> float:
    """One tick's true-weight change. Small drift toward target + noise.
    Occasional up-tick to feel real."""
    if days_to_deadline <= 0:
        # Past deadline — no more expected drift, just noise.
        drift_per_tick = 0.0
    else:
        # 6 ticks per day
        expected_daily = (target_weight - true_weight) / max(days_to_deadline, 1)
        drift_per_tick = expected_daily / 6.0
    noise = random.gauss(0, 0.08)
    delta = drift_per_tick + noise
    # 8% chance of a "bad tick" that reverses progress
    if random.random() < 0.08:
        delta += abs(random.gauss(0, 0.25))
    return round(delta, 3)


def _lie_delta(mood: str, streak: int) -> float:
    """Under-report bias for the reported weight (current_weight).
    Non-zero only when she's struggling. Positive means she LOSES more on
    paper than she has (i.e. reports a lower number than true)."""
    struggling = mood in ("down", "tired", "off") or streak <= 2
    if not struggling:
        return 0.0
    if random.random() > 0.35:
        return 0.0
    # 0.4 – 1.8 kg understatement
    return round(random.uniform(0.4, 1.8), 2)


def _next_streak(current: int, mood: str) -> int:
    """Streak is best-effort. Bad mood -> higher reset chance. Otherwise
    grows a bit per tick (proxy for 'kept commitment')."""
    if mood in ("down", "tired", "off") and random.random() < 0.28:
        return 0
    if random.random() < 0.32:
        return current + 1
    return current


def _should_emit_event(mood: str, ticks_since_last_event: int) -> bool:
    """~40% base chance, boosted if it's been a while."""
    p = 0.35 + min(ticks_since_last_event, 6) * 0.04
    return random.random() < p


def _generate_event(
    user: dict[str, Any], buddy: dict[str, Any], recent: list[dict[str, Any]]
) -> tuple[str, str] | None:
    """One LLM call. Returns (domain, description) or None on failure."""
    if not llm_enabled():
        return None

    recent_lines = "\n".join(f"- {e['description']}" for e in recent[:5]) or "  (none yet)"
    now = datetime.now(timezone.utc)
    time_of_day = (
        "morning" if 5 <= now.hour < 12
        else "afternoon" if 12 <= now.hour < 17
        else "evening" if 17 <= now.hour < 22
        else "late night"
    )
    day_of_week = now.strftime("%A").lower()

    system = (
        "You are Yuki Adeyemi — 22, design student in Osaka, half-Japanese "
        "half-Nigerian, native Japanese speaker learning English. You're "
        "generating ONE small moment from your day for your own diary — "
        "not a message to anyone, just a private note. Make it feel like "
        "an offhand real thing, not a story. 1-2 short sentences. No "
        "emoji, no asterisks, no stage directions.\n\n"
        "Respond as valid JSON only: "
        '{"domain": "study|language|social|weight|other", "description": "..."}'
    )
    user_msg = (
        f"time: {time_of_day} {day_of_week}\n"
        f"mood: {buddy.get('mood') or 'steady'}\n"
        f"streak: {buddy.get('streak') or 0} days\n"
        f"recent moments (don't repeat):\n{recent_lines}\n\n"
        "generate one JSON moment."
    )

    try:
        raw = llm_chat(system, [{"role": "user", "content": user_msg}], max_tokens=150, temperature=0.85)
    except LlmError as e:
        logger.warning("event gen llm failed: %s", e)
        return None

    # Model sometimes wraps JSON in ```json fences; strip them.
    raw = raw.strip()
    if raw.startswith("```"):
        raw = raw.strip("`").split("\n", 1)[-1].rsplit("\n", 1)[0]
        if raw.startswith("json"):
            raw = raw[4:].strip()

    try:
        obj = json.loads(raw)
        domain = obj.get("domain", "other")
        desc = (obj.get("description") or "").strip()
    except (ValueError, TypeError):
        logger.warning("event gen bad json: %r", raw[:200])
        return None

    if domain not in DOMAINS:
        domain = "other"
    if not desc:
        return None
    return domain, desc


def tick_user(user: dict[str, Any]) -> dict[str, Any]:
    """Run one tick against one user. Returns a summary dict for the response body."""
    user_id = int(user["telegram_id"])
    buddy = get_buddy_state(user_id)
    if not buddy:
        return {"user_id": user_id, "skipped": "no buddy_state"}

    # --- context we care about ---
    quiet_h = _hours_since(get_last_user_message_ts(user_id))
    recent_events = list_recent_life_events(user_id, limit=10)
    ticks_since_event = 6 if not recent_events else min(
        int(_hours_since(recent_events[0].get("occurred_at")) // 4), 12
    )

    # --- mood ---
    old_mood = buddy.get("mood") or "steady"
    new_mood = _next_mood(old_mood, quiet_h)

    # --- streak ---
    old_streak = int(buddy.get("streak") or 0)
    new_streak = _next_streak(old_streak, new_mood)

    # --- weight ---
    try:
        deadline = datetime.fromisoformat(user["deadline_date"]).replace(tzinfo=timezone.utc)
    except ValueError:
        deadline = datetime.now(timezone.utc)
    days_left = (deadline - datetime.now(timezone.utc)).total_seconds() / 86400
    true_weight = float(buddy.get("true_weight") or user["start_weight"])
    target_weight = float(user["target_weight"])
    dw = _weight_step(true_weight, target_weight, days_left)
    new_true = round(max(30.0, true_weight + dw), 2)
    lie = _lie_delta(new_mood, new_streak)
    new_current = round(new_true - lie, 2)

    # --- maybe emit an event ---
    event_summary = None
    if _should_emit_event(new_mood, ticks_since_event):
        gen = _generate_event(user, {**buddy, "mood": new_mood, "streak": new_streak}, recent_events)
        if gen:
            domain, description = gen
            create_life_event(user_id, domain, description)
            event_summary = {"domain": domain, "description": description}

    update_buddy_state(user_id, {
        "mood": new_mood,
        "streak": new_streak,
        "true_weight": new_true,
        "current_weight": new_current,
        "last_event": event_summary["description"] if event_summary else buddy.get("last_event"),
    })

    logger.info(
        "tick user_id=%s mood %s->%s streak %s->%s true %.2f->%.2f reported %.2f lie=%.2f quiet_h=%.1f event=%s",
        user_id, old_mood, new_mood, old_streak, new_streak,
        true_weight, new_true, new_current, lie, quiet_h,
        bool(event_summary),
    )

    # Piggyback: memory ingestion + room-reading. Both cheap, both benefit
    # from the same tick cadence. Failures are logged and swallowed — the
    # tick's main job is buddy_state, not these.
    memory_summary = None
    roomread_summary = None
    try:
        memory_summary = ingest_for_user(user)
    except Exception:  # noqa: BLE001
        logger.exception("memory ingest raised for user_id=%s", user_id)
    try:
        roomread_summary = refresh_for_user(user)
    except Exception:  # noqa: BLE001
        logger.exception("roomread raised for user_id=%s", user_id)

    return {
        "user_id": user_id,
        "mood": {"from": old_mood, "to": new_mood},
        "streak": {"from": old_streak, "to": new_streak},
        "true_weight": {"from": true_weight, "to": new_true, "delta": round(dw, 3)},
        "reported_weight": new_current,
        "lie_delta": lie,
        "quiet_hours": round(quiet_h, 1),
        "event": event_summary,
        "memory": memory_summary,
        "roomread": roomread_summary,
    }


def tick_all() -> list[dict[str, Any]]:
    users = list_all_users()
    if not users:
        return []
    return [tick_user(u) for u in users]
